[profile.default]
src = "contracts"
out = "out"
libs = [
	"lib",
	"lib/openzeppelin-contracts",
	"lib/openzeppelin-contracts-upgradeable"
]
solc = "0.8.24"
optimizer = true
optimizer_runs = 10000
ffi = false
gas_reports = [
	"SpokeYieldVault",
	"ControllerHub",
	"SuperVaultHub",
	"AaveV3Adapter",
	"VelodromeLPAdapter"
]
coverage = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
