name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  spec-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build
        run: forge build
      - name: Run SpecCompliance test only
        run: forge test -vvv --match-path test/spec/SpecCompliance.t.sol

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install deps
        run: |
          forge --version
          forge install --no-commit
      - name: Build
        run: forge build
      - name: Run tests
        run: forge test -vvv
      - name: Coverage
        run: forge coverage --report summary
      - name: Enforce coverage (lines >= 90%)
        run: |
          pct=$(forge coverage --report json | jq '.total.lines.pct')
          echo "Lines coverage: $pct"
          awk -v p="$pct" 'BEGIN { exit (p+0 >= 90.0) ? 0 : 1 }'

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Slither
        run: |
          pip install slither-analyzer solc-select
          solc-select install 0.8.24
          solc-select use 0.8.24
      - name: Run Slither
        run: |
          slither . --config-file .slither.json --filter-paths test/ --exclude-dependencies --ignore-compile --fail-high --fail-medium
